variables:
  TEST_RUN_TAG: \@bp
  TEST_IT_MVN_CLI_OPTS: -DtmsUrl=https://test-it.smart-consulting.ru -DtmsPrivateToken=SEdHamRnOHpTRVNGNkZ5OU1T -DtmsProjectId=4e4cdae5-3967-4bed-84ce-f7421c529dda -DtmsConfigurationId=f977e67d-58d3-4537-8965-57334e5d0ebe -DtmsAdapterMode=2 -DtmsAutomaticCreationTestCases=true -DtmsCertValidation=true
stages:
  - test
cache:
  paths:
    - $HOME/.m2

test:
  stage: test
  image:
    name: nexusrepo.smart-consulting.ru/markhobson/maven-chrome:jdk-8
  script:
    - mvn test $TEST_IT_MVN_CLI_OPTS "-Dcucumber.options=--tags $TEST_RUN_TAG"
